version: '3'

services:

  apache-php:
    restart: always
    build: apache-php
    expose:
      - 80
    volumes:
      - ./apache-php:/var/www/html/

  backend:
    restart: always
    build: backend
    secrets:
      - db-password
    # this port mapping exposes the REST API, it should be commented in production
    ports:
      - 8000:8000
    depends_on:
      - db

  db:
    image: postgres:14.1-alpine
    restart: always
    secrets:
      - db-password
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=example
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
    expose:
      - 5432
    
  nginx:
    restart: always
    image: nginx:1.21.4-alpine
    ports:
      - 80:80
      - 443:443
    environment:
      - NGINX_HTTP_PORT=80
      - NGINX_HTTPS_PORT=443
      - PUBLIC_SERVER_NAME=public_dns_name_here
    volumes:
      - ./templates:/etc/nginx/templates
      - ./data/nginx:/etc/nginx/conf.d
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    depends_on:
      - apache-php

  certbot:
    restart: always
    image: certbot/certbot:v1.21.0
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot

secrets:
  db-password:
    file: db/password.txt
